feat: added initial kanban components
NateNeslo/kanban-ui pull request #4
Opened 2024-01-22 11:21 UTC by NateNeslo

2024-01-22 12:07 UTC, noydb requested changes

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-item.tsx
> +      <div className={styles.btn}>btn-left</div>
Something that is clickable (like this element) in HTML should use an element that is itself clickable. While it will work if you make any element clickable in HTML, I think it's more correct to use a more semantically accurate element. So let's rather use a button here (and for `btn-right`), and then use CSS to style it appropriately

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-item.tsx
> +
Please delete two blank lines here. We want just one blank line between the function/component declaration, and the end of the import statements

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-item.module.css
> +}
I get what you're doing, but let's rather define these once we need them. To quote the dev principles:

"Always implement things when you _actually_ need them, never when you just _foresee_ that you need them.”

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-item.module.css
> +.container {
let's rather use a class called `kanban-item` or something like that, that more accurately conveys what the element is

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-board.tsx
> +import React from "react";
Pls use single quotes whenever possible. 

Again, absolutely nothing wrong, I'm just trying to align you with our standards & conventions

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-board.tsx
> +    <div>
One improvement we could make here, is perhaps to use an article element

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-board.tsx
> +const KanbanBoard = (props: props) => {
You could destructure these props immediately here to gain faster access to the specific values/props. 
```
({ category: KanbanCategory, itemList: KanbanItem[]}: props })
```

2024-01-22 12:07 UTC, noydb commented on src/components/kanban-board.tsx
> +  catagory: kanban.KanbanCatagory;
`catagory` -> `category`
`itemList` -> `items`

2024-01-22 12:17 UTC, noydb commented
Just a couple other questions/etc.:

- is there a specific reason you've named the css files `*.module.*`? Or is it more just a convention you've seen in the past? 
- I've never seen `import style from "styles.css"`, and then referencing values in the JSX (that are defined in the CSS). I had no idea you could that, I thought it was only possible in React Native. While it is cool, we don't really write it like that currently. But it does make me think that perhaps there is application to it. (like a small example: if I rename a class in the stylesheet, I don't have to manually rename it in the component/jsx as well).

2024-01-22 12:35 UTC, NateNeslo commented on src/types.d.ts
> +declare namespace kanban {
- From what I saw, that's how we can create global types in TS without using imports
- Although from this [StackOverflow](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript) answer, it seems that it's been discouraged from use.
- I should have used the `global` namspace instead of creating my own

2024-01-22 12:46 UTC, NateNeslo commented on src/types.d.ts
> +    export interface KanbanItem  {
Thank you for the advice, still going through the React Standards and noticed a few things I can change myself as well. Better to get it done with early on

2024-01-22 12:48 UTC, NateNeslo commented on src/components/kanban-board.tsx
> +import React from "react";
Not a problem, is there an eslint config for the standards I can use?

2024-01-22 12:56 UTC, NateNeslo commented
- In NextJS, you can use css modules to scope the styles to that specific component so you can have the same class name in different files
- It's the NextJS convention to have it like that, I think it makes it easier to notice which elements are similar in function.
- Of course we could still declare classes in the global module, albeit they would have unique names there.

2024-01-22 13:13 UTC, noydb commented on src/components/kanban-board.tsx
> +    <div>
yep

2024-01-22 13:14 UTC, noydb commented on src/components/kanban-board.tsx
> +import React from "react";
Yep lemme send it to you

2024-01-23 06:56 UTC, noydb requested changes

2024-01-23 06:56 UTC, noydb commented on src/app/page.tsx
> +"use client"
what is this?

2024-01-23 06:56 UTC, noydb commented on src/app/page.tsx
> +    <main className={styles.main}>
there should only be a single main element in an html page, please confirm this is the case. Also, let's rather use an ID here. I like the idea of css modules, but it's not a pattern we really follow at Neslo 👍 .

We currently use BEM for the most part, but I am trying to move us away from that as well (as I believe it pollutes the markup). I like minimal IDs, element selectors and pseudo selectors to achieve styling.

2024-01-23 06:56 UTC, noydb commented on src/app/page.tsx
> +import KanbanItem from "@/component/kanbanItem";
What is the `@` in this import path?

2024-01-23 06:56 UTC, noydb commented on src/component/kanbanBoard.tsx
> +interface props {
Capital letter when declaring an interface pls

2024-01-23 06:56 UTC, noydb commented on src/component/kanbanItem.module.css
css files should be all lowercase and use `hypen-case-like-so`. So this file should be `kanban-item.css`. 

Please also rename the component file to `KanbanBoard`, the file should start with a capital letter

2024-01-23 06:56 UTC, noydb commented on src/component/kanbanItem.tsx
> +    <div className={styles['kanban-item']}>
Let's rather declare the class here explicitly (`div className="kanban-item"`)

Please change the import statement to just: `import 'kanban-item.css';` And then declare the class explicitly for all other others. Please only declare the class if required. For example, we can style a button by doing: `div.kanban-item > button`. Instead of applying a class to button to achieve the same thing.

We must keep the markup as simple as possible when writing styles/classes/etc.

2024-01-23 06:57 UTC, noydb commented
Please align your next commit message with our standards doc as well 👍

2024-01-23 07:07 UTC, NateNeslo commented on src/app/page.tsx
> +"use client"
With NextJS, all components are server components by default, so I need to put that in this file since it uses useState which only works in client components

2024-01-23 07:14 UTC, NateNeslo commented on src/app/page.tsx
> +    <main className={styles.main}>
Yes, that's the only main on the page. 
I'll switch over from CSS modules as it makes it more unreadable imo when using BEM 
eg. `className={styles['kanban-item']}`

2024-01-23 07:23 UTC, NateNeslo commented on src/app/page.tsx
> +import KanbanItem from "@/component/kanbanItem";
The @ is for remapping local folders to a more readable format with Typescript. [Reference docs](https://www.typescriptlang.org/tsconfig#paths)

2024-01-23 07:35 UTC, NateNeslo commented on src/component/kanbanItem.tsx
> +    <div className={styles['kanban-item']}>
Okay great, I commented something similar above as well with regards to the first point. 

I tend to use classes for everything since that's how I've been used to doing it but will start using this method

2024-01-23 07:37 UTC, NateNeslo commented
> Please align your next commit message with our standards doc as well 👍

For this, I need some help figuring out git-flow and branching, since this project doesn't have an ID.
How should I format the project key and jira ID?

2024-01-23 08:50 UTC, noydb requested changes

2024-01-23 08:50 UTC, noydb commented on .eslintrc.json
> +    // "react-app/jest",
I don't think comments like this are valid in JSON

2024-01-23 08:50 UTC, noydb commented on src/app/page.tsx
> +    <main id="main">
can we make the ID more descriptive? to say main as the id is redundant, as the element/tag itself already semantically conveys this

2024-01-23 08:50 UTC, noydb commented on src/types.d.ts
> +declare namespace Kanban {
This is definitely cool, but I think for now, you can just export the enum & kanban item directly from this file, instead of wrapping inside a namespace. And then just rename this file to `types.ts`

2024-01-23 08:54 UTC, NateNeslo commented on .eslintrc.json
> +    // "react-app/jest",
Oh I didn't know JSON didn't support comments actually

2024-01-23 08:58 UTC, NateNeslo commented on src/types.d.ts
> +declare namespace Kanban {
Is there a naming convention for interfaces? There's conflicts with the KanbanItem component

2024-01-23 09:44 UTC, noydb commented on src/types.ts
> +  DONE = "Done",
use semi-colons to terminate here pls

2024-01-23 09:44 UTC, noydb commented on src/component/KanbanItem.tsx
> +        <div className="title">{props.title}</div>
use a span here pls

2024-01-23 09:44 UTC, noydb commented on src/component/KanbanItem.tsx
> +        <div className="description">{props.description}</div>
use a `p`

2024-01-23 09:45 UTC, noydb commented on src/app/page.tsx
> +    <main id="main-content">
Let's make the ID `login`

2024-01-23 09:45 UTC, noydb commented on src/app/page.tsx
can we also call this file something more descriptive? I think page is just the default when you setup the project write? Let's make it login or whatever accurately reflects the logic

2024-01-23 09:46 UTC, noydb commented on src/types.d.ts
> +declare namespace Kanban {
That's perfect for now

2024-01-23 09:49 UTC, NateNeslo commented on src/app/page.tsx
> +    <main id="main-content">
I plan to use another page for logging in, see comment below

2024-01-23 09:53 UTC, NateNeslo commented on src/app/page.tsx
With nextjs, the page.tsx is used to define that specific routes contents, it modularizes it in tandem with layout.tsx. 
It uses file-based routing so each route requires it's own page.tsx if it's a UI component, it will get wrapped by layout.tsx

2024-01-23 09:56 UTC, NateNeslo commented on src/types.ts
> +  DONE = "Done",
I can't, it's within the enum and it requires a comma for termination

2024-01-23 10:01 UTC, NateNeslo commented on src/app/page.tsx
> +    <main id="main-content">
On 2nd thought, I think the current approach is better

2024-01-23 11:01 UTC, noydb commented on src/types.ts
> +  DONE = "Done",
apologies, mistake from me

2024-01-23 11:04 UTC, noydb commented on src/component/KanbanItem/KanbanItem.tsx
> +        <p className="title">{props.title}</p>
The title should be a span, and the description should be a `p`, We can wrap them in a div (assuming the wrapping/parent element is necessary)

2024-01-23 11:04 UTC, noydb commented on src/types.ts
> +  catagory?: KanbanCategory;
`catagory` -> `category`

2024-01-23 11:05 UTC, noydb commented on src/component/KanbanItem/KanbanItem.tsx
directory name should be skeleton-case-like-this. THe file name is perfect. 

Sorry I realize this is a slightly confusing/clashing convention, but it's just how we do it at Neslo for react projects (I didn't pick this convention 😂 )

2024-01-23 11:13 UTC, NateNeslo commented on src/component/KanbanItem/KanbanItem.tsx
> +        <p className="title">{props.title}</p>
Okay got it, was a bit confused which one you were referring to

2024-01-23 11:13 UTC, NateNeslo commented on src/component/KanbanItem/KanbanItem.tsx
That's a bit strange but got it

2024-01-23 11:22 UTC, NateNeslo commented on src/app/KanbanView/page.tsx
This won't work in NextJS due to its app router, each folder gets mapped to a sub-directory in the URL so we'd end up with localhost:3000/kanban/board 
Unless we mark `kanban` as a RouteGroup: 
- `app/(kanban)/board` would result in localhost:3000/board etc

2024-01-23 11:40 UTC, noydb commented on src/app/KanbanView/page.tsx
oh jeepers okay. Don't worry then

2024-01-23 11:41 UTC, noydb approved these changes

2024-01-23 11:42 UTC, merged